CREATE TABLE `project-name.error_logging_dataset.error_log_table` (
  LOG_DATE DATETIME,
  PROJECT_NAME STRING,
  DATASET_NAME STRING,
  PROCEDURE_NAME STRING,
  ERROR_STATEMENT_TEXT STRING,
  ERROR_MESSAGE STRING,
  CUSTOM_MESSAGE STRING
);
